name: cdk
on:
  workflow_call:

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          cache: 'npm'
          cache-dependency-path: cdk
          node-version: lts/*

      - run: npm ci
        working-directory: cdk

      - run: npm run lint
        working-directory: cdk

      - run: npm run check
        working-directory: cdk

  unit-test:
    needs: lint-and-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          cache: 'npm'
          cache-dependency-path: cdk
          node-version: lts/*

      - run: npm ci
        working-directory: cdk

      - run: npm run test
        working-directory: cdk
